# This is a basic workflow to help you get started with Actions

name: GserverBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REPO_URL: https://github.com/lyrnstsen/Infinix.git
  REPO_BRANCH: master
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run delet script
        run: |
          rm -rf Infinix
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Out Of Update"
          git push origin main

      - name: Run a multi-line script
        run: |
          git clone $REPO_URL
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "UpdateFile"
          git push origin main
