# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REPO_URL: https://github.com/lyrnstsen/Asterix.git
  REPO_BRANCH: master

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run delet script
        run: |
          ls
          git clone $REPO_URL
          ln -sf /workdir/Asterix $GITHUB_WORKSPACE/Asterix
          cd
      - uses: actions/checkout@v1
      - uses: ./Asterix
        with:
          MY_NAME: "Mona"
